### ISSUE TITLE
Sprint  Backlog1-(Server dev)

### ISSUE THREAD

**Issue by SAT15** [sriramrathinavelu/attendanceSWE2015#11]

**Comment by SAT15** [comment]
@sriram 
Could you give a milestone for initial step up? Take this issue as a place to post your weekly tasks regarding Back end development

**Comment by sriramrathinavelu** [comment]
The tasks I have for this week are

1) Database schema design
2) API for CRUD operations (Creation/Updation/Deletion)
3) Basic prototype of ALIZE

**Comment by sriramrathinavelu** [comment]
Adding @TaniaSolo and @winddweb to the story board

**Comment by SAT15** [comment]
@sriramrathinavelu  DB schema done. (10/12)
