### ISSUE TITLE
Sprint  Backlog1-(Test Cases)

### ISSUE THREAD

**Issue by SAT15** [sriramrathinavelu/attendanceSWE2015#12]
@MahimaSrikanta  @shrutikamati 
 Treat this issue as a place to put your weekly tasks and do assign a milestone for it.

Your tasks for 1st sprint are
Generate test cases for FE screens

**Comment by sriramrathinavelu** [comment]
I have set the milestone as 1st sprint ... things we couldn't complete in this sprint, we will move into the next sprint...

**Comment by SAT15** [comment]
@shrutikamati @MahimaSrikanta 
This issue is carry forward to 2nd sprint

**Comment by SAT15** [comment]
I have moved this issue to 3rd sprint. That includes test cases based on PRD, and start testing 1 to 3 screens for Prof mockups @shrutikamati  @MahimaSrikanta

**Comment by SAT15** [comment]
Its completed.
