### ISSUE TITLE
Allot Test cases id# sync with PRD and Github

### ISSUE THREAD

**Issue by SAT15** [sriramrathinavelu/attendanceSWE2015#17]
@MahimaSrikanta @shrutikamati 
Allot unique id# to the test cases for prof's dashboard. i will snyc those id# to PRD and If require if will it inGithub too.

**Comment by SAT15** [comment]
I am carrying forward this issue to 2nd sprint

**Comment by MahimaSrikanta** [comment]
Test Case Ids have been allotted in Rally Development tool according to user story
