### ISSUE TITLE
Final  Software Architecture Showcase

### ISSUE THREAD

**Issue by SAT15** [sriramrathinavelu/attendanceSWE2015#2]
What do you think when we can have our software architecture ready? @sriramrathinavelu

**Comment by sriramrathinavelu** [comment]
Sat15, I don't understand what you mean by "showcase".

I will try to answer your question with best of my knowledge
We will have a django based rest end point which will use fastCGI to work with ALIZE to generate JSON responses for HTTP GET requests.
The server will use MongoDB as the database and we will have a rest API to access the data from the database as well.

Please let me know if this answers your questions. 

Thanks
Sriram

**Comment by SAT15** [comment]
Theoretical explanation sometimes is not that early, diagrammatic representation given a clear picture plus it is required for documentation, & it will help in different operations too.

**Comment by sriramrathinavelu** [comment]
Yes I will try to get it done in two or three days :)

**Comment by SAT15** [comment]
Great :+1:

**Comment by SAT15** [comment]
Can we use balsmiq to make the high level arch? I guess it can give a better look and feel to it? What say?

**Comment by sriramrathinavelu** [comment]
Am not sure ... If this is just for documentation, I will not be too particular about it....Anyways am busy with database schema design right now.So am closing this issue for now. We will think about it at a later point of time if it becomes important. Do you think that's acceptable ?

-Sriram
