### ISSUE TITLE
Update/Rework Student dashboard (wireframe)

### ISSUE THREAD

**Issue by SAT15** [sriramrathinavelu/attendanceSWE2015#20]
@SAT15 @shrutikamati 
due to loss of screen we need to re work on the student dashboard.. Let me know @shrutikamati  if you cant do it, Before this sprint ends.

**Comment by shrutikamati** [comment]
I can do it this weekend

**Comment by SAT15** [comment]
No problem ... i will see if i can do it before that.

**Comment by shrutikamati** [comment]
Ok. Let me know if you couldn't. I would like to do it.

**Comment by SAT15** [comment]
@shrutikamati .. you did it .. Hence I am closing it
