### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by shrutikamati** [sriramrathinavelu/attendanceSWE2015#30]
- [x]  Add splash screen

**Comment by winddweb** [comment]
Not sure what is this add splash screen means. Can you explain @shrutikamati ?

The app has had a splash screen already. It will only show on first launch. (Or try to kill the app from background and relaunch it will show the splash screen too)

**Comment by shrutikamati** [comment]
Yes it is working when I relaunch the app

**Comment by winddweb** [comment]
OK, so this is not a bug, right? I'll close it.
