### ISSUE TITLE
ITU_SAT Test Cases

### ISSUE THREAD

**Issue by SAT15** [sriramrathinavelu/attendanceSWE2015#4]
@MahimaSrikanta @kamatishruti
Girls, I guess you can start brainstorming and developing TEST CASES for first 3 screens using PRD Via Gdoc. It would be great if you both can start early this week so that we can foresight the issues and try to resolve them as a team ASAP. Since this is an early stage we are not having major milestone right now. We can again talk over later this week. Let me know If i would be of any help :)

**Comment by sriramrathinavelu** [comment]
Closing it as a duplicate of #12
