### ISSUE TITLE
ITU_SAT Android Development

### ISSUE THREAD

**Issue by sriramrathinavelu** [sriramrathinavelu/attendanceSWE2015#8]
Hi Tanya,

Can you start developing first 3 screens of our software updated in PRD shared via Gdoc.
It would be great if you can start early this week so that we can foresight the issues and try to resolve them as a team ASAP. Since this is an early stage we are not having major milestone right now. We can again talk over later this week. Please contact Ramshaa (SAT15) in case you have any queries

**Comment by sriramrathinavelu** [comment]
Adding @SAT15  and @winddweb as participants to the issue

**Comment by tatianasolonets** [comment]
Hi Sriram,
Ok, I think I can start on monday.

**Comment by sriramrathinavelu** [comment]
Closing this because #14 is created. This is just a duplicate
